class CidadeBairroModel {
  List<String> cidades = ['João Pessoa', 'Cabedelo', 'Santa Rita', 'Bayeux'];
  Map<String, List<String>> bairros = {
    'João Pessoa': [
      'Aeroclube',
      'Água Fria',
      'Altiplano',
      'Alto do Céu',
      'Anatólia',
      'Bairro das Indústrias',
      'Bancários',
      'Bessa ',
      'Brisamar',
      'Cabo Branco',
      'Castelo Branco',
      'Centro',
      'Cidade dos Colibris',
      'Cidade Verde',
      'Distrito Industrial',
      'Ernâni Sátiro',
      'Esplanada',
      'Estados',
      'Expedicionários',
      'Funcionários',
      'Gramame',
      'Ilha do Bispo',
      'Ipês',
      'Jardim 13 de Maio',
      'Jardim Luna',
      'Jardim Oceania',
      'João Agripino',
      'Manaíra',
      'Mandacaru',
      'Mangabeira',
      'Miramar',
      'Pedro Gondim',
      'Portal do Sol',
      'Róger',
      'São José',
      'Tambaú',
      'Tambauzinho',
      'Torre',
      'Valentina Figueiredo',
      'Varadouro',
    ],
    'Cabedelo': [
      'Amazônia Park',
      'Área Rural de Cabedelo',
      'Areia Dourada',
      'Camalaú',
      'Camboinha',
      'Centro',
      'Formosa',
      'Intermares',
      'Jacaré',
      'Jardim América',
      'Jardim Brasília',
      'Jardim Camboinha',
      'Jardim Manguinhos',
      'Monte Castelo',
      'Morada Nova',
      'Parque Esperança',
      'Parque Verde',
      'Poço',
      'Ponta de Campina',
      'Ponta de Matos',
      'Portal do Poço',
      'Recanto do Poço',
      'Renascer',
      'Salinas de Ribamar',
      'Santa Catarina',
    ],
    'Santa Rita': [
      'Área Rural de Santa Rita',
      'Bebelândia',
      'Capitão',
      'Centro',
      'Forte Velho',
      'Lerolândia',
      'Liberdade',
      'Municípios',
      'Odilândia',
      'Popular',
      'Ribeira',
      'Tambauzinho',
      'Várzea Nova',
      'Vila Tibiri',
    ],
    'Bayeux': [
      'Alto da Boa Vista',
      'Área Rural de Bayuex',
      'Baralho',
      'Brasília',
      'Centro',
      'Comercial Norte',
      'Imaculada',
      'Jardim Aeroporto',
      'Jardim São Severino',
      'Jardim São Vicente',
      'Manguinhos',
      'Mário Andreazza',
      'Mutirão',
      'Rio do Meio',
      'São Bento',
      'Sesi',
      'Tambay',
    ],
  };
}
